### ISSUE TITLE
Feature request: update values at runtime.

### ISSUE THREAD

**Issue by data-man** [Luukdegram/ctradix#3]
I tried this:

```zig
/// Update a value for the given `key`
/// Returns `false` if key is not found
/// Otherwise returns `true`
pub fn set(self: *Self, key: []const K, value: V) bool {
    var current = &self.root;
    var search = key;
    while (search.len != 0) {
        current = (current.edge(search[0]) orelse return false);

        if (startsWith(K, search, current.prefix, cmp))
            search = search[current.prefix.len..]
        else
            break;
    }

    if (current.leaf) |*leaf| {
       leaf.data = value; // <- Segmentation fault
       return true;
    }
    return false;
}
```
but got `Segmentation fault`. :(

**Comment by Luukdegram** [comment]
~~I don't think this would be possible without an allocator, which isn't something I want to add. (It was one of the benefits to me of making it comptime). However, I do see the benefit of offering this API. I'll leave this issue open for now in case I come up with an idea to handle this use case. Thank you for the suggestion!~~

EDIT: I thought more about it, and I'm actually not quite sure why this does not work. Unfortunately, I do not have time until the weekend to try it out.

**Comment by Luukdegram** [comment]
Limitation of how comptime works in Zig. The data is saved in the .rodata and therefore cannot be updated.
